openapi: 3.0.0
info:
  title: Notification Service API
  version: 1.0.0
  description: API documentation for the Notification Service

servers:
  - url: http://localhost:3001/v1
    description: Local server

components:
  schemas:
    Notification:
      type: object
      properties:
        _id:
          type: string
        userId:
          type: string
        message:
          type: string
        read:
          type: boolean
        __v:
          type: integer
      required:
        - _id
        - userId
        - message
        - read
        - __v
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /notifications:
    post:
      summary: Create a new notification
      tags:
        - Notifications
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                message:
                  type: string
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Notification"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    get:
      summary: Get notifications for the authenticated user
      tags:
        - Notifications
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: pageSize
          schema:
            type: integer
            minimum: 1
          required: false
          description: Number of notifications per page
        - in: query
          name: pageLimit
          schema:
            type: integer
            minimum: 1
          required: false
          description: Maximum number of pages to retrieve
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  notifications:
                    type: array
                    items:
                      $ref: "#/components/schemas/Notification"
                  page:
                    type: integer
                  limit:
                    type: integer
                  totalNotifications:
                    type: integer
                  totalPages:
                    type: integer
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /notifications/{id}:
    get:
      summary: Get a notification by ID
      tags:
        - Notifications
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Notification"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    put:
      summary: Mark a notification as read
      tags:
        - Notifications
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Notification"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
